version: "3.9"

services:
  app:
    build: .
    ports:
      - "5000:5000"
    env_file: .env
    environment:
      PORT: "5000"
      MQTT_BROKER: "mqtt://152.42.238.142:1883"
    networks:
      - infra-network
    restart: unless-stopped

networks:
  infra-network:
    external: true
