version: '3.9'

services:
  knit-production-backend-main:
    build:
      context: ./knit-production-backend-main
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "5000:5000"
    extra_hosts:
      - "host-gateway:host-gateway"
    networks:
      - app-network
    restart: unless-stopped

  knitt-production-client:
    build:
      context: ./knitt-production-client
      dockerfile: Dockerfile
    ports:
      - "3100:3100"
    depends_on:
      - knit-production-backend-main
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
